export const COLLECTION_TE = 'Consentir_Te'
export const COLLECTION_PEDIDOS = 'Pedidos'
export const CATEGORY = 'category'
export const CATEGORY_RECARGAS = 'recargas'
export const CATEGORY_CERAMICA = 'ceramica'